### ISSUE TITLE
你好，这个会不会被git把账号ban掉

### ISSUE THREAD

**Issue by lesnolie** [orange2008/drive-sync#1]
会不会属于滥用git然后ban账号呢？
感谢回答！

**Comment by dotfrankruan** [comment]
没有达到滥用标准，github只是说不能挖矿和爬虫，这个只是传文件，只要不传有版权的和一些全球范围内都违法的东西（比如儿童*情之类的），就没什么问题

**Comment by lesnolie** [comment]
哦哦，我以为流量大就会被封禁呢。
感谢感谢！！用着很舒服
已经不小心成功干翻我两个vps的流量了😭

Frank Ruan ***@***.***>于2021年11月28日 周日上午9:10写道：
